version: "3.9"

services:
  izzybot-client:
    ports:
      - "${IZZYBOT_CLIENT_OUTER_PORT_DEV}:${IZZYBOT_CLIENT_INNER_PORT_DEV}"
    env_file:
      - ./.env
      - ./client/.env.development
    environment:
      - NODE_ENV=development
  
  izzybot-server:
    ports:
      - "${IZZYBOT_SERVER_OUTER_PORT_DEV}:${IZZYBOT_SERVER_INNER_PORT_DEV}"
    env_file:
      - ./.env
      - ./server/.env.development
    environment:
      - NODE_ENV=development