# Build the app
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all source files
COPY . .

# Expose inner container port
EXPOSE 3000

# Command to start the app
CMD ["npm", "run", "dev"]