# Use Node Alpine for a lightweight image
FROM node:20-alpine

# Install build dependencies
RUN apk add --no-cache python3 make g++ git

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy all source files
COPY . .

# Expose inner container port
EXPOSE 3000

# Command to start the app
CMD ["sh", "-c", "npm run build-infinitepay-index && npm run dev"]