# Use Node Alpine for a lightweight image
FROM node:20-alpine

# Install build dependencies
RUN apk add --no-cache python3 make g++ git

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy all source files
COPY . .

# Conditionally build InfinitePay index 
RUN [ -d "./data/infinitepay_index" ] || npm run build-infinitepay-index

# Command to run tests
CMD ["npm", "test"]